kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv
  namespace: default
spec:
capacity:
  storage: 1Gi
accessModes:
  - ReadWriteOnce 
persistentVolumeReclaimPolicy: Retain
hostPath:
  path: /mnt/data
